[package]
name = "rust_bouncer"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.36", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1.0"
config = "0.14"
serde = { version = "1.0", features = ["derive"] }
dotenv = "0.15"
